### ISSUE TITLE
OSError: Unable to open file (file signature not found)

### ISSUE THREAD

**Issue by ling1220425528** [jofuelo/multimodal_emotion_detector#1]
I met a error"OSError: Unable to open file (file signature not found)".pealse help me!

**Comment by mlmyhero** [comment]
(vue-pyweb) J:\AI\vue-pyweb\multimodal_emotion_detector-master\multimodal_emotio
n_detector-master>python manage.py runserver
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\ml\Anaconda3\envs\vue-pyweb\lib\site-packages\django\core\manag
ement\__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "C:\Users\ml\Anaconda3\envs\vue-pyweb\lib\site-packages\django\core\manag
ement\__init__.py", line 363, in execute
    settings.INSTALLED_APPS
  File "C:\Users\ml\Anaconda3\envs\vue-pyweb\lib\site-packages\django\conf\__ini
t__.py", line 82, in __getattr__
    self._setup(name)
  File "C:\Users\ml\Anaconda3\envs\vue-pyweb\lib\site-packages\django\conf\__ini
t__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "C:\Users\ml\Anaconda3\envs\vue-pyweb\lib\site-packages\django\conf\__ini
t__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "C:\Users\ml\Anaconda3\envs\vue-pyweb\lib\importlib\__init__.py", line 12
7, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked    
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module       
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed  
  File "J:\AI\vue-pyweb\multimodal_emotion_detector-master\multimodal_emotion_de
tector-master\mysite\settings.py", line 34, in <module>
    AUDIOMODEL = load_model("modelos/audio_model.h5")
  File "C:\Users\ml\Anaconda3\envs\vue-pyweb\lib\site-packages\keras\utils\trace
back_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\ml\Anaconda3\envs\vue-pyweb\lib\site-packages\keras\saving\save
.py", line 206, in load_model
    raise IOError(f'No file or directory found at {filepath_str}')
OSError: No file or directory found at modelos/audio_model.h5
